# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171020_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
