# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171020_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_property',
        ),
    ]
