# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20171023_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
