# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20171025_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=80, null=True, unique=True),
        ),
    ]
